/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proxy.h"

void
proxy_fetch_prog_1(char *host, char *req) {
    CLIENT *clnt;
    enum clnt_stat retval_1;
    webpageResponse result_1;
    char * proxy_fetch_1_arg;

#ifndef	DEBUG
    clnt = clnt_create(host, PROXY_FETCH_PROG, PROXY_FETCH_VERS, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif	/* DEBUG */
    result_1.webPageContents = (char*) malloc(1024 * 1024 * 20);
    printf("Trying to fetch:%s\n",req);
    retval_1 = proxy_fetch_1(&req, &result_1, clnt);
    //printf("Expecting:%d, got:%d\n",RPC_SUCCESS,retval_1);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror(clnt, "call failed");
    }
    //printf("Received Contents:%s\n", result_1.webPageContents);
    free(result_1.webPageContents);
#ifndef	DEBUG
    clnt_destroy(clnt);
#endif	 /* DEBUG */
}

int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 3) {
        printf("usage: %s server_host weburl <testCaseFile>\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    if (argc == 3) {
        struct timeval startTime, endTime;
        //gettimeofday(&startTime, NULL);
        proxy_fetch_prog_1(host, argv[2]);
        //gettimeofday(&endTime, NULL);
        //printf("\nTotal Time: %lf milliseconds\n", (endTime.tv_sec - startTime.tv_sec)*1000.0 + (endTime.tv_usec - startTime.tv_usec) / 1000.0);
    } else {
        FILE* testFile;
        char line[1024];
        struct timeval startTime, endTime;
        testFile = fopen(argv[3], "r");
        if (testFile) {
            gettimeofday(&startTime, NULL);
            while (fgets(line, 100, testFile) != NULL) {
                printf("Read:%s\n",line);
                proxy_fetch_prog_1(host, line);
            }
            gettimeofday(&endTime, NULL);
            printf("\nTotal Time: %lf milliseconds\n", (endTime.tv_sec - startTime.tv_sec)*1000.0 + (endTime.tv_usec - startTime.tv_usec) / 1000.0);
            fclose(testFile);
        }
    }
    exit(0);
}
