/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROXY_H_RPCGEN
#define _PROXY_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct webpageResponse {
	char *webPageContents;
};
typedef struct webpageResponse webpageResponse;


#define PROXY_FETCH_PROG 0x23451111
#define PROXY_FETCH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROXY_FETCH 1
extern  enum clnt_stat proxy_fetch_1(char **, webpageResponse *, CLIENT *);
extern  bool_t proxy_fetch_1_svc(char **, webpageResponse *, struct svc_req *);
extern int proxy_fetch_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROXY_FETCH 1
extern  enum clnt_stat proxy_fetch_1();
extern  bool_t proxy_fetch_1_svc();
extern int proxy_fetch_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_webpageResponse (XDR *, webpageResponse*);
extern  bool_t xdr_webpageResponse (XDR *, webpageResponse*);

#else /* K&R C */
extern bool_t xdr_webpageResponse ();
extern bool_t xdr_webpageResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROXY_H_RPCGEN */
