/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proxy.h"

bool_t
xdr_webpageResponse (XDR *xdrs, webpageResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->webPageContents, 1024*1024*20))
		 return FALSE;
	return TRUE;
}
